-- 15 - Live Collaborative Session Notes (v107)
-- Stores append-only Yjs CRDT updates for each Session Note.

create table if not exists public.session_note_updates (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  session_note_id uuid not null references public.session_notes(id) on delete cascade,
  update_data text not null,
  is_seed boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists session_note_updates_note_id_idx
  on public.session_note_updates(session_note_id, id);

create unique index if not exists session_note_updates_one_seed_per_note_idx
  on public.session_note_updates(session_note_id)
  where is_seed = true;

alter table public.session_note_updates enable row level security;

grant select, insert on public.session_note_updates to authenticated;
grant usage, select on sequence public.session_note_updates_id_seq to authenticated;

drop policy if exists "Campaign members can read session note updates" on public.session_note_updates;
create policy "Campaign members can read session note updates"
on public.session_note_updates
for select
to authenticated
using (
  public.is_campaign_member(campaign_id)
  and exists (
    select 1 from public.session_notes s
    where s.id = session_note_id
      and s.campaign_id = session_note_updates.campaign_id
  )
);

drop policy if exists "Campaign members can add session note updates" on public.session_note_updates;
create policy "Campaign members can add session note updates"
on public.session_note_updates
for insert
to authenticated
with check (
  created_by = auth.uid()
  and public.is_campaign_member(campaign_id)
  and exists (
    select 1 from public.session_notes s
    where s.id = session_note_id
      and s.campaign_id = session_note_updates.campaign_id
      and s.is_deleted = false
  )
);

-- Realtime publication: add only if it is not already present.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'session_note_updates'
  ) then
    alter publication supabase_realtime add table public.session_note_updates;
  end if;
end $$;
